config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#home'
  get 'about', to: "frontend#about", as: "about"
  get 'services', to: "frontend#services", as: "services"
  get 'team', to: "frontend#team", as: "team"
  get 'clients', to: "frontend#clients", as: "clients"

  mount InyxContactUsRails::Engine, :at => '', as: 'messages'
  
  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/views/inyx_contact_us_rails/messages/_form.html.haml
#contact_us
  .container
    = render "layouts/frontend/messages"
    %h2
      Contacto
    .col-lg-7.col-md-7.col-sm-12.col-xs-12
      .content-form{style: "margin-top:5px;"}
        = form_tag({controller: "messages", action: "send_contact_message", method: "post"}, {class: "contact_form"}) do
          = text_field_tag :name, "", :class=>'form-control', :type => "text", :placeholder=>'Nombre', style: 'margin-bottom: 10px;'
          = text_field_tag :subject, "", :class=>'form-control', :type => "text", :placeholder=>'Asunto', style: 'margin-bottom: 10px;'
          = text_field_tag :email, "", :class=>'form-control', :type => "text", :placeholder=>'Email', style: 'margin-bottom: 10px;'
          = text_area_tag :content, "", :class=>'form-control' , :placeholder=>'Mensaje', style: 'margin-bottom: 10px; height: 150px;'
          #recaptcha_widget{:style => "display:block"}
            #recaptcha_image
            .input-group{ style:'margin-top: 5px; margin-bottom:10px;'}
              = text_field_tag :recaptcha_response_field, "",type: "text", id: "recaptcha_response_field", class: "form-control", placeholder: "Captcha"
              %span.input-group-btn
                = button_tag "<i class='fa fa-refresh'></i>".html_safe, :type => "button", class: "form-control", :onclick => "javascript:Recaptcha.reload(); return false;"
          = raw recaptcha_tags :display => { :theme => 'custom', lang: 'es' }, ajax: true
          = button_tag(type: 'submit', class: "btn btn-info", style:"width:100%") do
            %i.fa.fa-envelope.fa-2x
    .col-lg-5.info.col-md-5.col-sm-12.col-xs-12
      %p
        %label Dirección
        %br/
        %span Urbanización Adaro, Judibana, Falcon, Venezuela.

      %p
        %label Email
        %br/
        %span info@cygnuscon.net

      %p
        %label Teléfonos
        %br/
        %span +58 0414 - 693.03.22
        %br/
        %span +58 0414 - 696.69.91
      
      = image_tag "frontend/clientes/contact_logo.png", width: "150px", style: "margin-top: 30px; margin-bottom:30px; margin-left:0px;", class: "hidden-xs hidden-sm"

      %p
        %label Siguenos
        .content
          = link_to "#" do
            = image_tag "frontend/clientes/twitter.png", class: "socials"
          = link_to "#" do
            = image_tag "frontend/clientes/facebook.png", class: "socials"
        .content
          = link_to "#" do
            = image_tag "frontend/clientes/instagram.png", class: "socials"
          = link_to "#" do
            = image_tag "frontend/clientes/youtube.png", class: "socials"
        

= render "frontend/footer"

app/views/inyx_contact_us_rails/messages/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/messages', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading            
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, InyxContactUsRails::Message   
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los mensajes seleccionados?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
           
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            #table-scroll
              %table.grid{style: "width:100%", "ng-controller"=>"indexContact"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object);read(object);", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
                    - if can? :delete, InyxContactUsRails::Message
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td 
                      %i.fa.fa-envelope{'ng-show'=>"!object.read"}
                      %i.fa.fa-file-text-o{'ng-show'=>"object.read"}
                    %td {{ object.name }}
                    %td {{ object.subject }}
                    %td {{ object.created_at}} 
                    %td {{showclick}}             
                  %tr{"ng-show" => "!objects.length"}
                    %td{:style => "width:100%"}
                      %center
                        %i.fa.fa-frown-o
                        No hay Mensajes.
      
    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-envelope
                  Mensaje - {{ object_data.id }}
                - if can? :destroy, InyxContactUsRails::Message
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este mensaje?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove                
              .actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-envelope
                Mensaje
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;" }
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre: 
                  {{object_data.name}}
                  %br
                  %label Asunto: 
                  {{object_data.subject}}
                  %br
                  %label Correo electronico: 
                  {{object_data.email}}
                  %br/
                  %label Fecha:
                  {{object_data.created_at}}
                  %hr{style: "border:1px solid #4157d3"}
                  %p{align: "justify"}
                    {{object_data.content}}                  
                  %br/                  
                .attributes{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado un mensaje para mostrar.
        .show-footer

app/views/inyx_contact_us_rails/messages/_view_sm_xs.html.haml
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;", "ng-controller"=>"indexContact"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object);read(object);", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, InyxContactUsRails::Message 
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
					%td 
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.created_at}}
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							%i.fa.fa-envelope{'ng-show'=>"!object.read"}
							%i.fa.fa-file-text-o{'ng-show'=>"object.read"}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Mensajes.

app/views/inyx_contact_us_rails/messages/index.html.haml
= content_for(:title, "Admin - Mensajes")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/inyx_contact_us_rails/messages/new.html.haml
= content_for(:title, "Cygnus | Contacto")
= render 'form' 

app/views/inyx_contact_us_rails/messages/show.html.haml
= content_for(:title, "Admin - Mensajes | #{@message.subject}")
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"
%div
  .panel.panel-default{style:"margin-top:50px"}
    .panel-heading#heading-show{style:"padding-top:5px"}
      .actions
        .title.pull-left{ style: "margin-top:8px;" }
          %i.fa.fa-user
          Mensaje - 
          = @message.id
        - if can? :destroy, InyxContactUsRails::Message 
          = link_to message_path(@message), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
            %i.fa.fa-remove  

    .panel-body#body-show
      %label Nombre: 
      = @message.name
      %br
      %label Asunto: 
      = @message.subject
      %br
      %label Correo electronico: 
      = @message.email
      %br/
      %label Fecha:
      = @message.created_at.strftime("%d %B. %Y - %H:%M")
      %hr{style: "border:1px solid #4157d3"}
      %p{align: "justify"}
        = @message.content                 
      %br/                  